// Foster Calc · modo didático: explicação de cada linha da memória de cálculo.
// Chave = módulo; dentro, chave = texto da 1ª coluna da memória. Textos curtos, em linguagem de sala de aula.
window.FC_EXPLICA = {
  comum: {
    'Concreto / aço': 'C25 significa concreto com resistência característica à compressão (fck) de 25 MPa, ou seja, 95% dos corpos de prova rompem acima desse valor. CA-50 é o aço com tensão de escoamento (fyk) de 500 MPa.',
    'Resist. cálculo concreto': 'A norma não usa a resistência característica direto: divide o fck pelo coeficiente γc = 1,4 para cobrir variações do concreto da obra em relação ao corpo de prova. É a resistência "de projeto", fcd.',
    'Resist. cálculo aço': 'Mesma ideia do concreto, com coeficiente menor (γs = 1,15) porque o aço é industrializado e mais uniforme: fyd = 500/1,15 ≈ 435 MPa.',
    'Tração média': 'O concreto resiste pouco à tração (cerca de 10% da compressão). A fctm é usada para saber quando a peça fissura e para a aderência das barras.',
    'Tração de cálculo': 'Resistência à tração de projeto, usada na aderência (ancoragem) e na parcela do concreto que resiste ao cortante.',
    'Módulo secante': 'É a "rigidez" do concreto (quanto ele deforma sob tensão). Entra no cálculo das flechas e da fissuração.',
    'Cobrimento nominal': 'Espessura de concreto entre a barra mais externa e a face da peça. Protege o aço da corrosão e do fogo. Aumenta conforme a agressividade do ambiente (CAA I a IV).',
    'Cobrimento': 'Espessura de concreto entre a barra mais externa e a face da peça. Protege o aço da corrosão e do fogo. Aumenta conforme a agressividade do ambiente (CAA I a IV).',
    'Fatores de combinação': 'Nem toda carga acidental atua cheia ao mesmo tempo. ψ1 (frequente) e ψ2 (quase permanente) reduzem a acidental para verificar fissuração e flecha, que são situações de uso, não de ruptura.',
    'Momento de cálculo': 'O momento das cargas reais multiplicado por γf = 1,4. A peça é dimensionada para resistir a esse valor majorado, o que garante a margem de segurança contra a ruptura.',
    'Altura útil': 'Distância da face comprimida até o centro das barras tracionadas (d). É o "braço" que trabalha na flexão: quanto maior, menos aço é necessário.',
    'Linha neutra': 'Profundidade x, a partir da face comprimida, onde a tensão é zero. Acima dela o concreto comprime; abaixo, o aço traciona. Sai do equilíbrio entre a força no concreto e a força no aço.',
    'Ductilidade': 'Se x/d passa de 0,45, a peça romperia de forma brusca, esmagando o concreto antes do aço escoar. Limitar x/d garante que a viga avise (fissura e deforma) antes de romper.',
    'Armadura calculada': 'Área de aço que equilibra o momento de cálculo: As = Md / (fyd · z), onde z = d − 0,4x é o braço de alavanca entre as forças do concreto e do aço.',
    'Armadura mínima': 'Mesmo com momento pequeno, a norma exige um mínimo de aço para que, quando o concreto fissurar, o aço consiga absorver a força sem romper de repente.',
    'Abertura de fissuras': 'Concreto armado fissura sempre; o que se controla é a abertura (wk). Fissuras finas (0,2 a 0,4 mm, conforme o ambiente) não deixam a água chegar ao aço.',
    'Inércia equivalente': 'Depois de fissurar, a peça fica menos rígida. A fórmula de Branson mistura a inércia sem fissura e a fissurada conforme o tamanho do momento, para estimar a flecha real.',
    'Momento de fissuração': 'Momento a partir do qual o concreto tracionado começa a fissurar. Abaixo dele a peça trabalha "inteira" (estádio I).',
    'Flecha imediata': 'Deslocamento logo após o carregamento, com a carga quase permanente e a rigidez já reduzida pela fissuração.',
    'Flecha total': 'Com o tempo o concreto continua deformando sob carga (fluência). A norma multiplica a flecha imediata por (1 + αf); com carga aplicada cedo, αf fica perto de 1,3.',
    'Limite': 'Limite de aceitabilidade visual: L/250 do vão. Acima disso a deformação incomoda e pode trincar paredes e pisos.',
  },
  viga: {
    'Seção': 'Largura (bw) e altura (h) da viga. Uma regra prática inicial é h ≈ L/10 a L/12 para vãos internos.',
    'Bitolas': 'Diâmetro das barras longitudinais (Øl) e dos estribos (Øt), em mm.',
    'Largura dos apoios': 'Largura dos pilares onde a viga apoia. Define o espaço disponível para ancorar a armadura nos apoios de extremidade.',
    'Permanente': 'Cargas que estão sempre lá: peso próprio da viga (25 kN/m³ × área da seção), paredes e reações das lajes.',
    'Acidental': 'Cargas de uso (pessoas, móveis), que podem estar ou não. O programa alterna a acidental vão a vão para achar o pior caso (envoltória).',
    'Momento positivo máx.': 'Maior momento que traciona a face de baixo do vão, já majorado (×1,4). Define a armadura inferior.',
    'Cortante máx.': 'Maior força cortante de cálculo no trecho, normalmente junto aos apoios. Define os estribos.',
    'Momento negativo': 'Momento sobre os apoios internos: traciona a face de cima. Por isso a armadura negativa fica em cima e se estende para os dois lados do pilar.',
    'Tipo de apoio': 'Apoio interno (com viga dos dois lados, tem momento negativo) ou extremo (ponta da viga, onde a armadura inferior precisa ser ancorada).',
    'Adotado': 'Barras escolhidas com área igual ou maior que a necessária, respeitando o espaço entre barras para o concreto passar.',
    'Camadas': 'Se as barras não cabem lado a lado na largura da viga, vão em duas camadas, o que reduz um pouco a altura útil.',
    'Tensão no aço (freq.)': 'Tensão nas barras sob as cargas de uso. Quanto maior, mais abertas ficam as fissuras.',
    'Zona de aderência': 'Barras na parte de cima de peças altas têm aderência pior (o concreto ali fica mais poroso). A norma reduz a resistência de aderência nessa "má aderência".',
    'Ancoragem básica': 'Comprimento reto (lb) necessário para a barra transferir toda a sua força ao concreto por aderência.',
    'Ancoragem necessária': 'Comprimento real de ancoragem, reduzido quando há mais aço que o necessário ou quando se usa gancho.',
    'Extensão à esquerda': 'Até onde a armadura negativa precisa ir a partir do eixo do apoio: o ponto onde o momento deixa de precisar dela, mais a decalagem e a ancoragem.',
    'Extensão à direita': 'Até onde a armadura negativa precisa ir a partir do eixo do apoio: o ponto onde o momento deixa de precisar dela, mais a decalagem e a ancoragem.',
    'Cortante de cálculo': 'Força cortante majorada (×1,4) que os estribos e o concreto precisam resistir.',
    'Biela comprimida': 'O cortante forma "escoras" inclinadas de concreto comprimido (bielas). VRd2 é o limite antes delas esmagarem; se for ultrapassado, só aumentando a seção ou o fck.',
    'Parcela do concreto': 'Parte do cortante que o próprio concreto resiste (Vc), por engrenamento dos agregados e efeito de pino das barras. Os estribos pegam o resto.',
    'Asw/s calculado': 'Área de estribo por metro de viga necessária para o cortante que o concreto não absorve (modelo de treliça com bielas a 45°).',
    'Asw/s mínimo': 'Estribo mínimo exigido em qualquer viga, mesmo com cortante baixo, para evitar ruptura frágil por fissura inclinada.',
    'Espaçamento máximo': 'Estribos não podem ficar muito afastados, senão uma fissura inclinada passaria entre eles sem cruzar nenhum.',
    'Adotado (2 ramos)': 'Estribo fechado de dois "ramos" verticais, com diâmetro e espaçamento escolhidos para atender o Asw/s.',
    'Decalagem': 'O modelo de treliça faz a força na armadura de flexão ser maior do que o diagrama de momentos indica. Por isso o diagrama é "deslocado" (al) antes de cortar as barras.',
    'Força a ancorar': 'No apoio extremo, a armadura inferior ainda carrega uma força (por causa da decalagem) que precisa ser ancorada dentro do pilar.',
    'Armadura a ancorar': 'Área de barras que precisa chegar ao apoio extremo: a necessária para a força acima e, no mínimo, 1/3 da armadura do vão.',
    'Comprimento disponível': 'Espaço dentro do pilar para ancorar, descontado o cobrimento. Se for menor que o necessário, use gancho, grampo ou aumente o apoio.',
    'Momento atuante (q. perm.)': 'Momento com a carga quase permanente (g + ψ2·q), que é a que fica "a vida toda" e gera a flecha de longo prazo.',
  },
  laje: {
    'Vãos': 'lx é o menor vão e ly o maior, medidos entre eixos de apoio.',
    'Relação entre vãos': 'Se ly/lx ≤ 2, a laje trabalha nas duas direções (armada em cruz). Acima de 2, quase toda a carga vai na direção curta (armada em uma direção).',
    'Espessura': 'Altura da laje. Mínimos da norma: 8 cm para lajes de piso, 7 cm para cobertura sem balanço.',
    'Bordas': 'Apoiada: a laje pode girar sobre a viga. Engastada: continua na laje vizinha, que impede o giro e gera momento negativo nessa borda.',
    'Peso próprio': '25 kN/m³ × espessura. Uma laje de 10 cm pesa 2,5 kN/m².',
    'Permanente total': 'Peso próprio + revestimento, contrapiso, forro e paredes apoiadas na laje.',
    'Acidental': 'Carga de uso conforme a NBR 6120: 1,5 kN/m² para dormitório e sala, 2,0 a 3,0 para áreas de uso coletivo, por exemplo.',
    'Carga total': 'Soma permanente + acidental, usada no cálculo dos momentos e das reações.',
    'Materiais': 'Concreto e aço adotados. O aço de laje costuma ser CA-50 (ou CA-60 em telas e barras finas).',
    'Momento característico': 'Momento por metro de largura, calculado pela teoria das placas (a laje funciona como uma placa apoiada nas bordas). Positivo traciona em baixo; negativo, em cima sobre o engaste.',
    'Adotado': 'Barra e espaçamento escolhidos: diâmetro até h/8 e espaçamento até 2h ou 20 cm, o que for menor.',
    'Área efetiva': 'Área de aço que as barras adotadas realmente fornecem por metro.',
    'Área de influência': 'Pelo processo das charneiras, a laje é dividida em triângulos e trapézios (linhas a 45°, ou 60° a partir da borda engastada); cada pedaço descarrega na viga mais próxima.',
    'Reação por charneiras': 'Carga total da área de influência dividida pelo comprimento da viga: kN por metro de viga.',
    'Reação pela teoria das placas': 'Reação média calculada pela própria análise de placa. Costuma ser maior que a das charneiras em algumas bordas; o programa adota a maior, a favor da segurança.',
    'Reação característica adotada': 'Valor que vai para a viga: o maior entre os métodos. Use o botão "Usar na viga" para levar g e q direto ao módulo de vigas.',
    'Reação como laje em uma direção': 'Para ly/lx ≥ 2, a laje é tratada como uma faixa de viga entre as bordas longas: metade da carga para cada lado, ou 5/8 e 3/8 quando um lado é engastado.',
    'Cortante de cálculo': 'Reação majorada (×1,4) junto à borda.',
    'Resistência': 'Lajes normalmente não levam estribos: o concreto e a armadura de flexão resistem ao cortante (VRd1). Se não passar, aumenta-se a espessura.',
    'Carga quase permanente': 'g + ψ2·q: a parte da carga que fica atuando por longo tempo e provoca a flecha final.',
    'Momento atuante': 'Momento da carga quase permanente, comparado com o momento de fissuração para saber se a laje fissura.',
  },
  pilar: {
    'Seção': 'Dimensões do pilar. A norma pede no mínimo 19 cm; entre 14 e 19 cm é permitido, mas os esforços são majorados pelo coeficiente γn.',
    'Coeficiente adicional': 'γn aumenta as cargas de pilares finos (menor dimensão abaixo de 19 cm), porque neles um pequeno erro de execução pesa muito mais.',
    'Normal de cálculo': 'Força de compressão do pilar majorada: Nd = 1,4 × γn × Nk.',
    'Força normal reduzida': 'ν = Nd / (Ac · fcd): mostra quanto da capacidade de compressão do concreto está sendo usada. Entra no cálculo da curvatura e da armadura.',
    'Dimensão na direção': 'O pilar é verificado nas duas direções (x e y). Em cada uma, a dimensão h é a da seção paralela ao momento.',
    'Comprimento de flambagem': 'Distância entre pontos de inflexão da deformada. Em edifícios contraventados, normalmente é a distância entre pisos (le ≤ distância entre eixos das vigas).',
    'Esbeltez': 'λ = 3,46 · le / h. Quanto maior, mais o pilar tende a "embarrigar" (flambar). Este módulo cobre até λ = 90.',
    'Momento mínimo': 'Todo pilar tem imperfeições de execução. A norma exige considerar ao menos M1d,mín = Nd · (0,015 + 0,03·h), mesmo que o cálculo não mostre momento.',
    'Momento de 1ª ordem adotado': 'O maior entre o momento vindo das vigas (no topo ou na base) e o momento mínimo.',
    'Coeficiente αb': 'Ajusta o efeito de 2ª ordem conforme a distribuição do momento ao longo do pilar (momentos de sinais opostos nas pontas reduzem o efeito).',
    'Esbeltez limite': 'λ1: abaixo dele, o efeito de 2ª ordem (o deslocamento lateral aumentando o momento) é pequeno e pode ser desprezado.',
    'Considera 2ª ordem?': 'Se λ > λ1, o pilar deforma lateralmente e a carga ganha excentricidade extra; é preciso somar o momento de 2ª ordem.',
    'Curvatura': 'Método da curvatura aproximada: estima a curvatura na seção crítica a partir de ν e da altura da seção.',
    'Momento de 2ª ordem': 'M2d = Nd · le²/10 · (1/r): o momento extra causado pelo deslocamento lateral do pilar.',
    'Momento total': 'Momento de 1ª ordem (corrigido por αb) somado ao de 2ª ordem. É o que a armadura precisa resistir junto com a normal.',
    'Armadura máxima': 'No máximo 4% da seção fora das emendas (8% na região de emenda), para o concreto conseguir envolver as barras.',
    'Adotado': 'Número e diâmetro das barras, distribuídas no contorno. Mínimo de 4 barras (uma em cada canto) e diâmetro mínimo de 10 mm.',
    'Taxa geométrica': 'Área de aço dividida pela área da seção, em %.',
    'Bitola': 'Diâmetro das barras longitudinais: no mínimo 10 mm e no máximo 1/8 da menor dimensão da seção.',
    'Espaçamento livre mínimo': 'Espaço entre barras para o concreto e o vibrador passarem.',
    'Espaçamento máximo (eixos)': 'Distância máxima entre barras: 2 vezes a menor dimensão da seção, limitada a 40 cm.',
    'MRd em x (com Nd)': 'Momento resistente da seção armada na direção x, com a força normal atuando junto (flexão composta).',
    'MRd em y (com Nd)': 'Momento resistente na direção y, também com a normal.',
    'Aproveitamento crítico': 'Verificação da flexão oblíqua: combina os momentos nas duas direções. Até 100% a seção atende.',
    'Diâmetro': 'Estribo com no mínimo 5 mm e 1/4 do diâmetro das barras longitudinais.',
    'Espaçamento': 'Estribos a no máximo 20 cm, a menor dimensão da seção ou 12 vezes o diâmetro da barra longitudinal (CA-50).',
    'Proteção contra flambagem': 'Os estribos seguram as barras longitudinais para que elas não "estourem" para fora. Barras de canto ficam protegidas pelo próprio estribo.',
    'Barras sem proteção': 'Barras intermediárias a mais de 20 vezes o diâmetro do estribo do canto precisam de grampo suplementar.',
  },
};
